services:
  odoo:
    container_name: rumah_buku_odoo
    image: odoo:19.0
    env_file: .env
    depends_on:
      - odoo-postgres
    ports:
      - "8069:8069"
    volumes:
      - ./etc/odoo:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./var/lib/odoo:/var/lib/odoo
    command: odoo --dev=all

    networks:
      - odoo-network
  odoo-postgres:
    container_name: odoo-postgres
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-network
    

networks:
  odoo-network:
    driver: bridge

volumes:
  odoo-db-data:

