[options]
admin_passwd = $pbkdf2-sha512$600000$hbB2LoXw/h/jfG.tFUJIiQ$W6VmdIjTSPB0CB50YlDZkLEtwr5FDNOVUNE.haiDy7ZrdJLAEoNuqeCsIG8SYmf.hRj2VsTLgbrosz4N32dSug
db_host = odoo-postgres
db_user = odoo
db_password = odoo
db_port = 5432
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
